import {test} from 'node:test';
import assert from 'node:assert/strict';
import {spawnSync} from 'node:child_process';
import {mkdtemp,readFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {profileSchema,quote,port,slug,unit,containerId,absolutePath,writeFile} from '../src/core/validation';
import {parsePorts,parseSnapshot,parseSections,inventoryScript} from '../src/core/inventory';
import {buildPlan,recipeScript,recipes,parseEnv} from '../src/core/recipes';
import {awgDockerfile} from '../src/core/vpn';
import {Storage} from '../src/core/storage';
import type {Profile} from '../src/shared/types';
const profile:Profile={id:'eb6492d9-1006-4e7a-bf00-cafab912f980',name:'test',host:'203.0.113.10',port:22,username:'root',auth:'password',keyPath:'',sudo:false};
const enc=(key:string,text:string,code=0)=>`__VPST_SECTION__${key}:${code}\n${Buffer.from(text).toString('base64')}\n`;
const fixture=enc('system','test-vps\nx86_64\n6.8.0\n0\n2\n0.3 0.2 0.1 1/9 5\nup 3 days\nUTC')+enc('os','ID=ubuntu\nPRETTY_NAME="Ubuntu 24.04 LTS"')+enc('memory','MemTotal: 4000000 kB\nMemAvailable: 1000000 kB')+enc('disk','Size Used Avail Use% Mounted\n10000 8700 1300 87% /')+enc('ports','tcp LISTEN 0 128 0.0.0.0:5432 0.0.0.0:* users:(("postgres",pid=4,fd=7))\nudp UNCONN 0 0 [::1]:53 [::]:*')+enc('services','ssh.service loaded active running SSH\nfailed.service loaded failed failed Error')+enc('ssh','passwordauthentication yes\npermitrootlogin yes')+enc('ufw','Status: inactive')+enc('nft','permission denied',1)+enc('iptables','permission denied',1)+enc('projects','/opt/app/package.json\n/opt/app/compose.yaml\n/opt/бот/requirements.txt')+enc('containers','{"ID":"abcdef123456","Names":"bot","Image":"bot:1","State":"running","Ports":"","Labels":"com.docker.compose.project=bot"}')+'__VPST_END__';
const snapshot=parseSnapshot(fixture,22);
test('shell quoting treats adversarial text as data',()=>{for(const value of ["'; touch /tmp/NO; '",'$(whoami)','`id`','line1\nline2','тест " кавычки']){const r=spawnSync('bash',['-c','printf %s '+quote(value)],{encoding:'utf8'});assert.equal(r.status,0);assert.equal(r.stdout,value);}});
test('validation rejects injection and invalid ranges',()=>{for(const x of ['0','65536','22;id','2.5','-1','1e3'])assert.throws(()=>port(x));assert.throws(()=>slug('a;id'));assert.throws(()=>unit('sshd.service; reboot'));assert.throws(()=>containerId('--help'));assert.throws(()=>absolutePath('/opt/../etc/shadow'));assert.throws(()=>quote('\0'));});
test('profile never persists credentials or unknown properties',()=>{const p=profileSchema.parse({...profile,password:'secret',token:'secret'});assert.equal('password'in p,false);assert.throws(()=>profileSchema.parse({...profile,host:'server;id'}));});
test('file transfer encoding safely writes arbitrary content',async()=>{const dir=await mkdtemp(join(tmpdir(),'vpst-'));try{const path=join(dir,'config');const value='hello\n$(echo no)\n\' "\nUnicode: привет';const r=spawnSync('bash',['-s'],{input:writeFile(path,value),encoding:'utf8'});assert.equal(r.status,0);assert.equal(await readFile(path,'utf8'),value);}finally{await rm(dir,{recursive:true,force:true});}});
test('port parser handles IPv4, IPv6 and unusual addresses',()=>{const p=parsePorts('tcp LISTEN 0 128 [::]:443 [::]:* users:(("xray",pid=5,fd=8))\nudp UNCONN 0 0 127.0.0.1:53 0.0.0.0:*\ntcp LISTEN 0 128 [::1]:2860 [::]:*');assert.equal(p.length,3);assert.deepEqual(p.map(p=>p.exposed),[true,false,false]);assert.equal(p[0].port,443);});
test('inventory preserves unicode and reports failures without claiming safety',()=>{assert.equal(snapshot.hostname,'test-vps');assert.equal(snapshot.memoryTotal,4096000000);assert.equal(snapshot.projects.length,2);assert.equal(snapshot.projects[0].kind,'Compose');assert.ok(snapshot.projects.some(x=>x.path==='/opt/бот'));assert.ok(snapshot.findings.some(f=>f.level==='danger'&&f.detail.includes('5432')));assert.ok(snapshot.findings.some(f=>f.title.includes('не подтверждена')));assert.ok(snapshot.findings.some(f=>f.title.includes('ошибкой')));});
test('truncated scan fails closed',()=>{assert.throws(()=>parseSections(fixture.replace('__VPST_END__','')));});
test('missing port permission is not interpreted as no listeners',()=>{const s=parseSnapshot(fixture.replace(enc('ports',snapshot.sections.ports.text),enc('ports','permission denied',1)),22);assert.ok(s.findings.some(f=>f.title==='Список портов недоступен'));});
test('environment handles literal dollar signs without Compose interpolation',()=>{assert.deepEqual({...parseEnv('TOKEN=$a${b}\nEMPTY=\n# skip')},{TOKEN:'$$a$${b}',EMPTY:''});assert.throws(()=>parseEnv('INVALID LINE'));assert.equal(parseEnv('__proto__=safe').__proto__,'safe');});
test('managed scripts pass Bash parser for every recipe',()=>{
 for(const recipe of recipes){const p=Object.fromEntries(recipe.fields.map(f=>[f.key,f.default||'']));Object.assign(p,{password:'test-password-only-123',domain:'app.example.com',key:'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFakePublicKeyOnly',image:'nginx:1.28-alpine',repo:'https://github.com/v1waa/example.git',commit:'a'.repeat(40)});const script=recipeScript(recipe.id,p,profile,22);const check=spawnSync('bash',['-n'],{input:script,encoding:'utf8'});assert.equal(check.status,0,recipe.id+': '+check.stderr);}
});
test('scripts include fresh port checks and refuse overwrite',()=>{for(const id of ['postgres','mariadb','redis','xray','wdtt','awg','static','proxy']){const script=recipeScript(id,{name:'test',password:'test-pass-12345',domain:'site.example.com',html:'<h1>Test</h1>'},profile,22);assert.match(script,/Порт .* уже занят/);assert.match(script,/Путь уже существует/);}});
test('databases only publish loopback and generate remote secrets',()=>{for(const id of ['postgres','mariadb','redis']){const script=recipeScript(id,{name:'test'},profile,22);assert.match(script,/openssl rand -hex 24/);const payload=[...script.matchAll(/printf %s '([A-Za-z0-9+/=]+)' \| base64 -d/g)].map(m=>Buffer.from(m[1],'base64').toString());assert.ok(payload.some(s=>s.includes('127.0.0.1:')));assert.ok(payload.some(s=>s.includes('db_password')));}});
test('VPN binary hashes and commits are pinned, no curl pipe bash',()=>{for(const id of ['wdtt','xray']){const script=recipeScript(id,{password:'test-pass-12345'},profile,22);assert.match(script,/sha256sum -c -/);assert.doesNotMatch(script,/curl.*\|.*bash/);}assert.match(awgDockerfile,/[0-9a-f]{40}/);});
test('WDTT panel seed binds loopback and hashes password',()=>{const password='test-secure-secret';const script=recipeScript('wdtt',{password},profile,22);assert.ok(!script.includes(password));const payload=[...script.matchAll(/printf %s '([A-Za-z0-9+/=]+)' \| base64 -d/g)].map(m=>Buffer.from(m[1],'base64').toString());const seed=JSON.parse(payload.find(s=>s.includes('password_hash'))!);assert.equal(seed.webListen,'127.0.0.1');assert.equal(seed.subEnable,false);assert.match(seed.password_hash,/^\$2[aby]\$/);});
test('dangerous identifiers and invalid actions are blocked',()=>{assert.throws(()=>buildPlan({type:'service',id:'ssh.service',verb:'stop'},profile,'s',snapshot,22));assert.throws(()=>buildPlan({type:'container',id:'abc123def456',verb:'rm'},profile,'s',snapshot,22));assert.throws(()=>buildPlan({type:'compose',id:'/etc',verb:'up'},profile,'s',snapshot,22));assert.throws(()=>buildPlan({type:'read-config',id:'/etc/shadow'},profile,'s',snapshot,22));assert.throws(()=>buildPlan({type:'recipe',id:'docker'},profile,'s',null,22));});
test('firewall confirms only after a different SSH session',()=>{const p=buildPlan({type:'recipe',id:'ufw-confirm'},profile,'session-test',snapshot,2222);assert.match(p.command,/firewall-session/);assert.match(p.command,/!= 'session-test'/);const enable=buildPlan({type:'recipe',id:'ufw-enable',params:{ports:'80/tcp,51820/udp'}},profile,'session-test',snapshot,2222);assert.match(enable.command,/ufw allow 2222\/tcp/);assert.match(enable.command,/on-active=120s/);assert.equal(enable.risk,'critical');assert.throws(()=>buildPlan({type:'recipe',id:'ufw-enable'},profile,'s',snapshot,0));});
test('plan is session-bound and expires',()=>{const p=buildPlan({type:'service',id:'nginx.service',verb:'restart'},profile,'session-1',snapshot,22);assert.equal(p.session,'session-1');assert.ok(p.expiresAt>Date.now());assert.ok(p.expiresAt<Date.now()+301000);});
test('storage reloads without secrets and marks interrupted work',async()=>{const dir=await mkdtemp(join(tmpdir(),'vpst-store-'));try{const s=new Storage(dir);await s.load();await s.saveProfile({...profile,password:'NEVER_SAVE_THIS'});await s.record({id:'op',title:'Test',host:'localhost',startedAt:new Date().toISOString(),status:'running'});const content=await readFile(join(dir,'state.json'),'utf8');assert.ok(!content.includes('NEVER_SAVE_THIS'));const next=new Storage(dir);await next.load();assert.equal(next.data.journal[0].status,'interrupted');}finally{await rm(dir,{recursive:true,force:true});}});
test('inventory script is syntactically valid and contains no secret reads',()=>{assert.equal(spawnSync('bash',['-n'],{input:inventoryScript}).status,0);assert.doesNotMatch(inventoryScript,/cat.*(?:shadow|panel\.db|\.env|private|id_rsa)/);});
test('embedded Python in every generated installer parses correctly',()=>{
 for(const recipe of recipes){const p=Object.fromEntries(recipe.fields.map(f=>[f.key,f.default||'']));Object.assign(p,{password:'test-password-only-123',domain:'app.example.com',key:'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFakePublicKeyOnly',image:'nginx:1.28-alpine',repo:'https://github.com/v1waa/example.git',commit:'a'.repeat(40)});const script=recipeScript(recipe.id,p,profile,22);
 for(const m of script.matchAll(/<<'(PY|VPST_SUBNETS)'\n([\s\S]*?)\n\1/g)){const r=spawnSync('python3',['-c','import ast,sys;ast.parse(sys.stdin.read())'],{input:m[2],encoding:'utf8'});assert.equal(r.status,0,recipe.id+': '+r.stderr);}
 }
});
