import { _electron as electron } from 'playwright';
import {mkdtemp,mkdir,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {resolve,join} from 'node:path';
import assert from 'node:assert/strict';
import ssh2 from 'ssh2';
const {Server,utils}=ssh2;
const config=await mkdtemp(join(tmpdir(),'vpst-ui-'));
await mkdir('test-results',{recursive:true});
const sshKey=utils.generateKeyPairSync('ed25519');
const enc=(key,text,code=0)=>`__VPST_SECTION__${key}:${code}\n${Buffer.from(text).toString('base64')}\n`;
const audit=enc('system','smoke-server\nx86_64\n6.8\n0\n2\n0.2 0.1 0.1\nup 1 hour\nUTC')+enc('os','ID=ubuntu\nPRETTY_NAME="Ubuntu 24.04"')+enc('memory','MemTotal: 4000000 kB\nMemAvailable: 2000000 kB')+enc('disk','Size Used Avail Use% Mounted\n1000000 100000 900000 10% /')+enc('services','nginx.service loaded active running Nginx')+enc('ports','tcp LISTEN 0 128 0.0.0.0:2222 0.0.0.0:*')+enc('ssh','passwordauthentication no')+'__VPST_END__';
let execCount=0;
const server=new Server({hostKeys:[sshKey.private]},client=>{client.on('error',()=>{});client.on('authentication',ctx=>{if(ctx.method==='password'&&ctx.password==='test-password')ctx.accept();else ctx.reject();});client.on('ready',()=>client.on('session',accept=>{const s=accept();s.on('exec',accept=>{const stream=accept();let data='';stream.on('data',b=>data+=b.toString());stream.on('end',()=>{if(data.includes('SSH_CONNECTION'))stream.write('127.0.0.1 12345 127.0.0.1 2222\n0\n');else if(data.includes('__VPST_SECTION__'))stream.write(audit);else{execCount++;stream.write('SMOKE_OPERATION_OK\n');}stream.exit(0);stream.end();});});}));});
await new Promise(r=>server.listen(0,'127.0.0.1',r));
const args=[resolve('.')];if(process.platform==='linux')args.push('--no-sandbox','--disable-gpu');
let app;
try{
 app=await electron.launch({args,env:{...process.env,XDG_CONFIG_HOME:config,APPDATA:config},timeout:45000});
 const page=await app.firstWindow();const errors=[];page.on('pageerror',e=>errors.push(String(e)));
 await page.getByRole('heading',{name:'Сервер под контролем.'}).waitFor();
 assert.equal(await page.evaluate(()=>typeof window.vps?.state),'function');
 assert.equal(await page.evaluate(()=>typeof window.require),'undefined');
 await page.screenshot({path:'test-results/welcome.png'});
 await page.getByRole('button',{name:'Посмотреть демо'}).click();
 await page.getByText('demo-frankfurt',{exact:true}).waitFor();
 await page.screenshot({path:'test-results/dashboard.png'});
 for(const label of ['Проекты','Службы','Контейнеры','Порты и сеть','Защита','Базы данных','Сайты и боты','VPN и туннели','Система','Журнал операций','Консоль']){
  await page.locator('nav').getByRole('button',{name:label,exact:true}).click();
  assert.ok(await page.getByRole('heading',{level:1,name:label,exact:true}).isVisible(),label);
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth),false,'horizontal overflow '+label);
 }
 await page.locator('nav').getByRole('button',{name:'VPN и туннели',exact:true}).click();
 await page.screenshot({path:'test-results/vpn.png',fullPage:true});
 await page.getByRole('button',{name:'Клиент AmneziaWG',exact:false}).click();
 await page.getByRole('dialog').waitFor();await page.keyboard.press('Escape');
 await app.evaluate(({BrowserWindow,dialog})=>{BrowserWindow.getAllWindows()[0].setSize(1080,800);dialog.showMessageBox=async()=>({response:1,checkboxChecked:false});});
 await page.locator('nav').getByRole('button',{name:'Обзор',exact:true}).click();
 await page.screenshot({path:'test-results/dashboard-1080.png'});
 await page.getByRole('button',{name:'Сервер',exact:true}).click();
 await page.getByLabel('Название',{exact:true}).fill('Smoke VPS');
 await page.getByLabel('IP или имя хоста',{exact:true}).fill('127.0.0.1');
 await page.getByLabel('SSH-порт',{exact:true}).fill(String(server.address().port));
 await page.getByLabel('Способ входа',{exact:true}).selectOption('password');
 await page.getByLabel('Пароль SSH',{exact:true}).fill('test-password');
 await page.getByRole('button',{name:'Подключиться',exact:true}).click();
 await page.getByText('smoke-server',{exact:true}).waitFor({timeout:30000});
 assert.equal(await page.getByText('SSH подключён',{exact:true}).count(),1);
 await page.locator('nav').getByRole('button',{name:'Консоль',exact:true}).click();
 await page.getByRole('button',{name:'Посмотреть план',exact:true}).click();
 await page.getByRole('dialog').getByRole('button',{name:'Выполнить на VPS'}).waitFor();
 assert.equal(await page.getByRole('button',{name:'Выполнить на VPS'}).isDisabled(),true);
 await page.getByPlaceholder('127.0.0.1',{exact:true}).fill('127.0.0.1');
 await page.getByRole('button',{name:'Выполнить на VPS'}).click();
 await page.getByRole('log').filter({hasText:'SMOKE_OPERATION_OK'}).waitFor();
 await page.getByText('Готово',{exact:true}).waitFor();assert.equal(execCount,1);
 await page.screenshot({path:'test-results/operation.png'});
 await page.getByRole('button',{name:'Свернуть вывод'}).click();
 await page.getByRole('button',{name:'Отключиться',exact:true}).click();
 assert.equal(errors.length,0,errors.join('\n'));
 console.log('Desktop UI smoke passed: IPC isolation, 12 pages, SSH login, scan, critical plan, command, disconnect.');
}catch(error){if(app)await (await app.firstWindow()).screenshot({path:'test-results/failure.png'}).catch(()=>{});throw error;}finally{if(app)await app.close();server.close();await rm(config,{recursive:true,force:true}).catch(()=>{});}
