import type {Snapshot,API} from '../shared/types';
import {recipes} from '../shared/catalog';
export const demoSnapshot:Snapshot={
 at:new Date().toISOString(),hostname:'demo-frankfurt',os:'Ubuntu 24.04 LTS',osId:'ubuntu',arch:'x86_64',kernel:'6.8.0-79-generic',uptime:'up 18 days, 6 hours',cpuCount:2,load:0.34,memoryTotal:4294967296,memoryUsed:1395864371,diskTotal:64424509440,diskUsed:18038862643,privileged:true,sshPort:22,timezone:'Europe/Moscow',
 ports:[{protocol:'tcp',address:'0.0.0.0',port:22,process:'sshd',exposed:true},{protocol:'tcp',address:'0.0.0.0',port:443,process:'caddy',exposed:true},{protocol:'tcp',address:'127.0.0.1',port:5432,process:'docker-proxy',exposed:false},{protocol:'udp',address:'0.0.0.0',port:51820,process:'docker-proxy',exposed:true},{protocol:'tcp',address:'127.0.0.1',port:2860,process:'wdtt-app',exposed:false}],
 services:[{name:'ssh.service',state:'active',detail:'OpenBSD Secure Shell server'},{name:'docker.service',state:'active',detail:'Docker Application Container Engine'},{name:'fail2ban.service',state:'active',detail:'Fail2Ban Service'},{name:'wdtt.service',state:'active',detail:'WDTT server and local panel'},{name:'cron.service',state:'active',detail:'Regular background program processing daemon'}],
 containers:[{id:'abc123def456',name:'alertvi-bot-1',image:'ghcr.io/example/bot:1.0.0',state:'running',ports:'',project:'alertvi'},{id:'bcd234efg567',name:'postgres-database-1',image:'postgres:17-bookworm',state:'running',ports:'127.0.0.1:5432->5432/tcp',project:'postgres'},{id:'cde345fab678',name:'website-web-1',image:'caddy:2.10-alpine',state:'running',ports:'80, 443',project:'website'}],
 projects:[{name:'alertvi',path:'/opt/alertvi',kind:'Compose',evidence:'compose.yaml'},{name:'website',path:'/opt/vps-tuner/website',kind:'Compose',evidence:'compose.yaml'},{name:'postgres',path:'/opt/vps-tuner/postgres',kind:'Compose',evidence:'compose.yaml'}],
 findings:[{level:'warning',title:'SSH принимает пароли',detail:'Проверьте вход по ключу перед отключением аутентификации паролем.'},{level:'ok',title:'Fail2ban запущен',detail:'Служба защиты SSH активна.'},{level:'info',title:'Обнаружены правила firewall',detail:'Проверьте IPv6, внешний firewall и публикацию Docker-портов.'},{level:'ok',title:'База данных на localhost',detail:'PostgreSQL доступен через SSH-туннель.'}],sections:{network:{code:0,text:'Демонстрационные данные. Подключите VPS для реального аудита.'},ufw:{code:0,text:'Status: active\n22/tcp ALLOW Anywhere\n443/tcp ALLOW Anywhere'}}
};
const unavailable=async():Promise<any>=>{throw new Error('Подключение доступно в desktop-приложении. Этот просмотр показывает только интерфейс.');};
export const previewAPI:API={state:async()=>({profiles:[],journal:[],connection:{connected:false,busy:false},version:'0.1.0',recipes}),saveProfile:unavailable,deleteProfile:unavailable,selectKey:unavailable,connect:unavailable,disconnect:unavailable,scan:unavailable,plan:unavailable,execute:unavailable,tunnel:unavailable,closeTunnels:unavailable,download:unavailable,exportReport:unavailable,exportOutput:unavailable,openExternal:async url=>{window.open(url,'_blank','noopener,noreferrer');},subscribe:()=>()=>{}};
